### ISSUE TITLE
Caret can go out of the users view when inserting numbers

### ISSUE THREAD

**Issue by stevenjob** [ScottLogic/finput#41]
Steps to reproduce:

1) Go to [here](http://scottlogic.github.io/finput/)
2) type in lots of numbers (more than can fit in the input box)
When typing lots of numbers the caret goes out of the users view

**Comment by oriondean** [comment]
Nice spot

Wherever possible we should always try to stay as close to the native input implementation where possible

**Comment by ryanggrey** [comment]
@stevenjob does the workaround proposed in https://github.com/ScottLogic/finput/pull/63 help?
