### ISSUE TITLE
Demo does not work on moblie

### ISSUE THREAD

**Issue by stevenjob** [ScottLogic/finput#43]
Specifically Android 7.1.1

**Comment by msuperina** [comment]
How is the demo accessed on android ? Is this using a browser ? If so is it related to https://github.com/ScottLogic/finput/issues/110 which has a PR awaiting for approval ?

**Comment by stevenjob** [comment]
yep, yep, approved

**Comment by msuperina** [comment]
@stevenjob I forgot to mention this issue in this PR https://github.com/ScottLogic/finput/pull/115
It should be fixed in the next release.
Can we closed here as the PR mentions a similar issue https://github.com/ScottLogic/finput/issues/110 ?

**Comment by stevenjob** [comment]
yep
