### ISSUE TITLE
Refresh github page

### ISSUE THREAD

**Issue by oriondean** [ScottLogic/finput#44]
The finput github page (http://scottlogic.github.io/finput/) is looking rather basic and still states it is maintained by Ali at the bottom.

Give this page a new lick of paint and update any relevant outdated areas

**Comment by sh1989** [comment]
The "Usage" section also links to the old github page. This section is entirely irrelevant as the input is displayed above.

In Firefox, the finput component is not usable, because:
```
404 Not Found - GET https://rawgit.com/alisd23/finput/master/dist/finput.min.js
The resource from “https://rawgit.com/alisd23/finput/master/dist/finput.min.js” was blocked due to MIME type mismatch (X-Content-Type-Options: nosniff)
ReferenceError: finput is not defined
```

**Comment by ryanggrey** [comment]
`dist` directory has been removed from `master` branch, so I think this will be broken in all browsers. Also, I think ownership has moved from alisd23 to ScottLogic which we'll need to recognise in the url.
