### ISSUE TITLE
Auto-formatting applied too soon in IE11

### ISSUE THREAD

**Issue by rwilliams-scottlogic** [ScottLogic/finput#45]
I want to enter 12
I press 1
The input formats immediately, resulting in "1.00" with the cursor at the end

In Chrome/FF, formatting only happens when I leave the field.

**Comment by rcassonScottLogic** [comment]
i believe this is due to a `for...of` loop {finput.js 152:5} not playing well with babel/IE11 

i have a work around which is too implement the loop without the `of` although i'm currently looking into why babel isn't transpiling it correctly.
