### ISSUE TITLE
Allow keypresses that don't amend field value

### ISSUE THREAD

**Issue by oriondean** [ScottLogic/finput#51]
When i focus in on the input field and press f5 my refresh is blocked since preventDefault blocks all keypresses rather than just ones that would affect the field value.

**Comment by rcassonScottLogic** [comment]
so i could add an action type in for all the function keys. then allow the default behaviour on those keypresses? but theres also keys like pageup/pagedown

**Comment by oriondean** [comment]
I'd include as many keys as possible that don't amend the field value, that would include page up/down

**Comment by rcassonScottLogic** [comment]
is there any reason we need to preventDefault?

**Comment by rcassonScottLogic** [comment]
i have re worked it slightly,

now only printable characters have there default actions prevented. and only if they haven't been handled previously
