### ISSUE TITLE
Allow for manual setting of options

### ISSUE THREAD

**Issue by sh1989** [ScottLogic/finput#57]
It would be nice if there was a manual function call to allow for setting of options at a later date, without having to tear down and recreating a `finput`. This would be useful if, for example, you are displaying an amount in relation to a currency pair (so the number of decimals is pertinent). If the user then changes a currency pair, this could result in the number of decimals needing to be changed.

A simple `setOptions` would suffice :)

**Comment by ryanggrey** [comment]
PR https://github.com/ScottLogic/finput/pull/76

**Comment by ryanggrey** [comment]
@sh1989 I assumed we wanted to keep `setOptions` as a pure setter so it does not redraw the element. The user can do this by retrieving current rawValue and setting it back. Does this fit with your example use case?
