### ISSUE TITLE
e.key is not defined on Chrome 47

### ISSUE THREAD

**Issue by hannimator** [ScottLogic/finput#65]
Using chrome 47.0.2526.80 and e.key is not defined.

**Comment by rwilliams-scottlogic** [comment]
https://caniuse.com/#feat=keyboardevent-key
available since Chrome 51, May 2016

**Comment by rwilliams-scottlogic** [comment]
Bug makes a case for doing Browserstack #33

**Comment by ryanggrey** [comment]
Might also be wise for us to be clear about our browser support policy and publicise via README.

**Comment by ryanggrey** [comment]
This can hopefully be used for browsers that don't support `event.key` - https://www.npmjs.com/package/keyboardevent-key-polyfill

**Comment by ryanggrey** [comment]
PR https://github.com/ScottLogic/finput/pull/69

**Comment by ryanggrey** [comment]
@hannimator Are we good to close this issue given the polyfill workaround for older browsers?

**Comment by hannimator** [comment]
Sure
