### ISSUE TITLE
Migrate to using `selenium-webdriver` directly

### ISSUE THREAD

**Issue by ryanggrey** [ScottLogic/finput#67]
At the moment we're using `wdio`. Not sure if that gives us much over using `selenium-webdriver` directly. I've ran into a couple of automation issues where it wasn't clear if the problem was in `wdio` or indirectly through `selenium-webdriver`. Using it directly might help to remove ambiguity like this. However I'm not very experienced with `wdio` so there might be good reasons for using it that I haven't considered.

**Comment by chrisprice** [comment]
Might be worth reviewing https://github.com/chrisprice/react-app-webdriver

**Comment by ryanggrey** [comment]
PR #77
