### ISSUE TITLE
Copy and paste breaks input when pasting value featuring delimiter into field

### ISSUE THREAD

**Issue by oriondean** [ScottLogic/finput#80]
If i paste in a value into finput that contains the decimal delimiter (e.g. Hello.World) then it's treated a valid paste and the field updates to `NaN.00`

The field should not update when invalid numbers are pasted into the field

**Comment by gordongovan** [comment]
This looks like it's been fixed in 1.1.1, `helpers.rawToFormatted` will not return `NaN.00` any more.

**Comment by msuperina** [comment]
I can confirm when pasting `Hello.World` the value of the finput field does not change.
