### ISSUE TITLE
IE11 allows users to enter numpad `+-*/` into input

### ISSUE THREAD

**Issue by ryanggrey** [ScottLogic/finput#86]
Reported by user. I haven't tried replicating this. Probably worth checking if issue exists in other browsers too.

**Comment by gordongovan** [comment]
See the note below this section: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values#Numeric_keypad_keys

> While older browsers used words like "Add", "Decimal", "Multiply", and so forth modern browsers identify these using the actual character ("+", ".", "*", and so forth).

I can confirm that IE11 and Edge do indeed use these instead of the character.
