### ISSUE TITLE
Delete key not processed on IE and Edge

### ISSUE THREAD

**Issue by gordongovan** [ScottLogic/finput#93]
IE and Edge use `Del` instead of `Delete` for `KeyboardEvent.key` when <kbd>Delete</kbd> is pressed.
Finput doesn't capture this and fails to process the key press leaving it to default browser behaviour.

Whenever you make a change with <kbd>Delete</kbd> that would need to cause a reformat of the field the cursor jumps to the end of the input.

**To repeat:**
With IE or Edge on http://scottlogic.github.io/finput/ enter `123.00` and place the cursor after `3`.
Press <kbd>Delete</kbd>.

**Expected:**

12,300 (as seen on Firefox and Chrome)

**Actual**

12,300.00

**Comment by ryanggrey** [comment]
PR #95 should fix this
