### ISSUE TITLE
Finput blocks many browser shortcuts

### ISSUE THREAD

**Issue by gordongovan** [ScottLogic/finput#94]
When a finputted element has focus many keyboard shortcuts don't work.

- Some are swallowed - <kbd>Alt</kbd>+<kbd>D</kbd>
- Some unexpectedly change the value in finput - <kbd>Ctrl</kbd>+<kbd>K</kbd>

---
**To repeat**

With input element having focus press <kbd>Alt</kbd>+<kbd>D</kbd>

**Expected:**

Browser address bar should be focused.

**Actual:**

Input element retains focus. (On Firefox and Chrome. IE and Edge behave as expected)

---
**To repeat**

With input element having focus press <kbd>Ctrl</kbd>+<kbd>K</kbd>

**Expected:**

Browser search tool should be focused.

**Actual:**

Input element retains focus and value multiplied by 1000.

**Comment by ryanggrey** [comment]
I'm not sure it's possible to fix this without manually identifying every browser shortcut for every browser and OS combination (as well as any differences across browser version numbers).

For example <kbd>Alt</kbd>+<kbd>D</kbd>:
- macOS/Chrome: is **not** a browser shortcut. In fact <kbd>Alt</kbd> is a modifier key which allows `∂` to be typed. So we should prevent default to avoid `∂` being added to the finput field.
- Windows/Chrome: is a shortcut to focus address bar so we should **not** prevent default to allow the shortcut keys to be handled by the browser.

I can't find any in-built way to detect what the browser will identify as a shortcut. It would also help if DOM event handling (updating inputs etc.) and browser event handling (address bar focus etc.) were somehow distinct allowing us to prevent one but not the other, but again I can't find a way to do this. I think we're left with manually listing keyboard shortcuts per browser/OS and allowing default behaviour in these cases. This feels like it would be a large amount of effort for a result that will likely be error prone and brittle.

**Comment by gordongovan** [comment]
I was hoping that if alt/ctrl were pressed then you could just let the browser handle it, I forgot about <kbd>Alt</kbd>+ something inputing special chars. That throws a spanner into my thinking.

Oh well. This wasn't a major blocker. Just a minor irritation.

**Comment by ryanggrey** [comment]
I'll continue to think about this and I've mentioned it to the other finput contributors so I will revisit if a new idea is raised.

**Comment by ryanggrey** [comment]
I found a way to generalise across macOS and Windows the keys that may result in browsershortcuts - https://github.com/ScottLogic/finput/pull/101
